services:
  go:
    container_name: go
    build:
      context: ./
    volumes:
      - ./:/app
      - .env:/app/.env
    networks:
      - infrastructure

networks:
  infrastructure:
    driver: bridge
    external: true